### ISSUE TITLE
Inference time compute bug

### ISSUE THREAD

**Issue by jefby** [soon-yau/QNN#4]
In file https://github.com/soon-yau/QNN/blob/master/01_Intro_to_TFlite.ipynb, there is some code like below:
```python
print("inference time: %.1f ms"%(100*elapsed))
```

time.time() return value is second, if you get micro second, you should multiply by 1000.

**Comment by soon-yau** [comment]
Indeed it's a typo, it should have been 1000.

**Comment by soon-yau** [comment]
This has now been corrected. Thanks.
