### ISSUE TITLE
interpreter._get_tensor_details

### ISSUE THREAD

**Issue by VincentChong123** [soon-yau/QNN#5]
Hi @soon-yau ,

at https://github.com/soon-yau/QNN/blob/master/01_Intro_to_TFlite.ipynb
>However, there is no way to find out how many tensors are there, 

What do you think about finding it this way
it works for [mobilenet_v1](http://download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_0.25_224_quant.tgz) , I have not checked with other models.

```
num_layer =interpreter.get_output_details()[0]['index']+2  #ori: 89, 
for i in range(num_layer):
  details = interpreter._get_tensor_details(i)
  print(i, details['name'])
```

**Comment by soon-yau** [comment]
I have just tried to convert a custom model, and unfortunately there doesn't seem to be a fixed relationship between input and output indices.
